### ISSUE TITLE
Does minification work with django-distill?

### ISSUE THREAD

**Issue by venteto** [meeb/django-distill#56] opened 2022-07-10 04:09 UTC
I have essentially copied your example site and started tweaking it ([demo](https://djistx.gitlab.io/) | [repo](https://gitlab.com/djistx/djistx.gitlab.io/)),

I have [django-htmlmin](https://pypi.org/project/django-htmlmin/) installed and it works just fine until I try to distill the site, then it is just ignored, and nothing is minified. I've tried different ideas from their docs to make it work for the distilled site as well, but I just cannot seem to figure anything out.

I'm just wondering if it is incompatible with `django-distill`, or if not, how would I make it work with the generated static site?

After I got this working, I was going to try using [django-compressor](https://django-compressor.readthedocs.io/en/stable/) for CSS, SASS and JS as well, but maybe you already know if this is is or is not compatible with `django-distill` too?

Thanks!

**Comment by meeb** [comment] 2022-07-10 04:25
Internally `django-distill` uses parts of the Django testing framework to render HTML, so in theory it'll support anything that the Django renderer natively supports. I know tag-based in-template filters work (e.g. `{% sass_src 'styles/distill.scss' %}` for SASS) and middleware based filters should work.

I can only assume your minification process isn't triggered with Django's testing framework either for some reason. Can you check it with this:

```bash
$ python manage.py shell
```
and then in the python shell:

```python
>>> from django.conf import settings
>>> settings.ALLOWED_HOSTS.append('testserver')
>>> from django.test import Client
>>> c = Client()
>>> response = c.get('/')
>>> print(resposen.content)
```

This should render the HTML generated by your `/` index page using the Django testing framework into the terminal. Check if that is minified. If it is minified, then the issue is probably somewhere in `django-distill` and how it calls the test framework, if it's not minified then it's probably something to do with `django-htmlmin` and not being triggered when running through the test framework.

**Comment by venteto** [comment] 2022-07-10 04:36
Thank you for your response. I followed your instructions, and it is minified in the shell:

![Screenshot from 2022-07-10 00-34-50](https://user-images.githubusercontent.com/7062385/178131395-d4546b68-45ab-42e9-be1c-32e70fc7e2eb.png)

**Comment by meeb** [comment] 2022-07-10 04:47
OK, can you try this as well? In the Django shell for your project:

```python
>>> from django.conf import settings
>>> settings.ALLOWED_HOSTS.append('testserver')
>>> from django.test import RequestFactory
>>> from django.http import HttpResponse
>>> from apps.blog.views import IndexView
>>> request_factory = RequestFactory()
>>> request = request_factory.get('/')
>>> response = IndexView.as_view()(request)
>>> response.render()
>>> print(response.content)
```

**Comment by meeb** [comment] 2022-07-10 08:33
After looking into it this was caused by some middleware not being loaded in some situations. I've pushed a fix that will be in the next release. Thanks for the issue.

**Closed** 2022-07-10 08:32 UTC

**Comment by meeb** [comment] 2022-07-10 08:42
The middleware fix is now in the 2.10.0 release pushed to PyPI, please update with pip or whatever package manager you are using.

**Comment by venteto** [comment] 2022-07-10 13:50
Thank you again for your help. I bumped the version and pushed the changes to my GitLab repo, but it still does not seem to minify anywhere but with `runserver`. I even tried using a production settings file with debug turned off in my Makefile, but it makes no difference. I also tried your second set of shell instructions, and it does still minify in the shell as well:

![distill-minify-shell-test](https://user-images.githubusercontent.com/7062385/178147201-0d459ee4-1442-4a51-99c9-3f08d2e979a2.png)

![distill-minify-shell-test-prod](https://user-images.githubusercontent.com/7062385/178147624-82c7dc6a-6d46-4796-a96e-a4eac625cdd8.png)

**Comment by meeb** [comment] 2022-07-10 14:14
Neither of your last screenshots have minification enabled, so that's showing the middleware isn't loaded properly. I've just pushed a minor tweak that might fix it. Please update to 2.10.1 from PyPi and try again.

**Comment by venteto** [comment] 2022-07-10 14:25
Oh wow, that is perfect, it works now! Thank you so much!

**Comment by meeb** [comment] 2022-07-10 14:26
No problem, glad you got it working.
